### ISSUE TITLE
Problem with the repetitive sequence

### ISSUE THREAD

**Issue by k3yavi** [10XGenomics/rust-debruijn#10]
Hi guys,

May be I misunderstood something, but I think there could be a potential bug in the debruijn graph generation with super repetitive sequence. Imagine the following case:

```
AAAAATAAAATAAAATAAAATAAAATAAAATAAAATAAAATAAAA
```
It's a 45 length sequence with the following sequence `A` + `AAAAT`* 8 + `AAAA`.

I am curious what should be the right debruijn graph for this with 31 kmer size and strandedness as false (there is a potential problem with that too as msp and filter kmer assumes complementary definition of strandedness flag but assume we correct for it) i.e. I do want to canonicalize the kmers,

If I ran it correctly then this library gives the following gfa:
```
H       VN:Z:debruijn-rs
S       0       AAAAATAAAATAAAATAAAATAAAATAAAAT
L       0       +       1       +       30M
S       1       AAAATAAAATAAAATAAAATAAAATAAAATAAAAT
P       ENST00000375105.7|ENSG00000117215.14|OTTHUMG00000002701.1|OTTHUMT00000007683.1|PLA2G2D-001|PLA2G2D|2672|UTR5:1-59|CDS:60-497|UTR3:498-2672|     0+,1+,1+        *
```
NOTE: I added the `P` flag and it was not available by default although `L` and `S` are available by default.
However twopaco, another library gives the following entries:

```
H       VN:Z:1.0
S       15      ATTTTATTTTATTTTATTTTATTTTATTTTT
S       8       AAAATAAAATAAAATAAAATAAAATAAAATAAA
S       12      ATTTTATTTTATTTTATTTTATTTTATTTTAT
P       ENST00000375105.7|ENSG00000117215.14|OTTHUMG00000002701.1|OTTHUMT00000007683.1|PLA2G2D-001|PLA2G2D|2672|UTR5:1-59|CDS:60-497|UTR3:498-2672|     15-,8+,12-,8+,12-,8+    *
```

 
If I follow the P values from the second gfa I can recreate the input fasta sequence. However, the size of the recreated sequence from the first gfa would be shortened by 4 bases, I think because of the repetitive sequences. Not sure how twopaco handles it (my hunch is by maintaining the reference sequence info ?) but I think this is a problem and mot sure how can we tackle it.

Let me know if you guys have any thoughts.

**Comment by pmarks** [comment]
Hi Avi, thanks for the report -- the correct cDBG is getting assembled in your example, but there is a bug in the gfa export code that was causing links that join opposite ends of the same sequence to be missing.  Fix is now on master. I added your example as a test case, thanks.

Here's the new GFA:
```
H	VN:Z:debruijn-rs
S	0	AAAAATAAAATAAAATAAAATAAAATAAAAT
L	0	+	1	+	30M
S	1	AAAATAAAATAAAATAAAATAAAATAAAATAAAAT
L	1	-	1	-	30M
```

re msp - I think I should just get rid of the rc argument -- it's always a safe to set it to true.  That just causes canonical pairs of kmers to alway end up in the same shard - it doesn't affect the assembly result.

**Comment by k3yavi** [comment]
Hi @pmarks ,
Thanks for the super fast response !
I think there is still a problem, let me try to show that with the examples:
`S	0	AAAAATAAAATAAAATAAAATAAAATAAAAT` This is of length 31; total length = 31
`S	1	AAAATAAAATAAAATAAAATAAAATAAAATAAAAT` this is of length 35; total length = 31+35-30(shared kmer) = 36
Because of `L	1	-	1	-	30M`  1 and and 1 are connected again so total length 36+35-30 = 41

After traversing the de bruijn graph the total length is coming to 41 while I gave the input raw fasta of length 45 bases. I think the 4 bases are getting lost when merging the debruijn graphs but if you follow the unitigs in the second gfa it will come to exact 45 bases.

**Comment by k3yavi** [comment]
May be my assumption is wrong that I can recreate the input raw sequence by parsing the dbg ?
but the parsing would like following for rust-debruijn:
```
AAAAATAAAATAAAATAAAATAAAATAAAAT
 AAAATAAAATAAAATAAAATAAAATAAAATAAAAT
      AAAATAAAATAAAATAAAATAAAATAAAATAAAAT
```

while parsing for twopaco for the same raw fasta sequence, looks like the following:
```
AAAAATAAAATAAAATAAAATAAAATAAAAT
 AAAATAAAATAAAATAAAATAAAATAAAATAAA
    ATAAAATAAAATAAAATAAAATAAAATAAAAT
      AAAATAAAATAAAATAAAATAAAATAAAATAAA
         ATAAAATAAAATAAAATAAAATAAAATAAAAT
           AAAATAAAATAAAATAAAATAAAATAAAATAAA
```
In both the cases each row is a untig which share 30 bases from the row above it

**Comment by k3yavi** [comment]
Yep I see the problem although not sure if it fits in the de-novo world however, *if* we know the reference sequence then we are not using the information from the terminal kmer of the input and indeed the `twopaco` gfa is doing the right thing. If I disallow the merging of the terminal kmer into a unitig then at least with pen and paper I can recreate the de bruijn graph as reported by twopaco from which we can parse and create the input raw sequence. Although not sure how and where should I disallow the merge of terminal kmer, may be while assembling shards I have to use `exts` but still have to think about it.

**Comment by pmarks** [comment]
You can construct the original sequence by stopping in the middle of the 35bp unitig (which is a valid thing to do).  A compressed DBG should put those kmers into a single unitig, unless you have some other rule that specifies when not to merge unbranched paths. You wouldn't want a general purpose cDBG construction to care about where in the input sequences each kmer came from, otherwise it would compress a lot less than it could.

  The `join_test` [method](https://github.com/10XGenomics/rust-debruijn/blob/master/src/compression.rs#L36) of `CompressionSpec` lets you customize that behavior compression behavior based on metadata about the kmers -- that was we used in the pseudoaligner to prevent kmers with different equivalence classes from getting merged.

**Comment by k3yavi** [comment]
Thanks Pat, it makes sense. I'll customize it for my use case.
