### ISSUE TITLE
Should we slice when continuous shards are going to the same bucket ?

### ISSUE THREAD

**Issue by k3yavi** [10XGenomics/rust-debruijn#11]
Hi guys,

I was thinking of another optimization but wasn't sure of its impact on overall pipeline. The thought is the following:

If you look at [this](https://github.com/10XGenomics/rust-debruijn/blob/master/src/msp.rs#L126-L137) part of the msp bucketing, I propose to replace this with the following:
```
    let mut min_positions = Vec::with_capacity(16);
    let mut min_pos = find_min(0, k - p);
    let mut min_pos_history = min_pos;
    min_positions.push((0, min_pos));

    for i in 0..(m - k + 1) {
        if i > min_pos {
            min_pos = find_min(i, i + k - p);

            if pval(min_pos) != pval(min_pos_history) {
                min_pos_history = min_pos;
                min_positions.push((i, min_pos));
            }
        } else {
            let test_min = pmin(min_pos, i + k - p);
            if test_min != min_pos {
                unreachable!();
                //min_pos = test_min;
                //min_positions.push((i, min_pos));
            }
        }
    }

```
My thought was if continuous shards with different min_pos yet going to same bucket, do we have to splice the super sequence ? What I did here was maintain the first min_pos and if the next min_pos is going to the same bucket I don't add it as a splice point. 
Please let me know your thoughts if it can create any corner case.

**Comment by pmarks** [comment]
The code has the nice property that the slices that come out of it are guaranteed to be at most 2k - p bases long, which lets us pack them into a 'fixed-size' container data structure like the `Lmer`  (with some unused bits).  This lets us avoid calling malloc to get memory to store the slice, and makes serializing and deserializing it much faster. The unused bits in the Lmer will get compressed away on disk by a compression algorithm like gzip or lz4. Supernova for example relies on this property.

The rate at which successive slices will have the same minimizer is `~ 1/n_buckets`, which will be small, so you won't see much advantage on average from this change. 

Make sense?

**Comment by k3yavi** [comment]
That makes sense, thanks for the explanation .
